import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";

import MusicWrapper from "@/components/MusicWrapper";

export const metadata: Metadata = {
  title: "Dream Null",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MusicWrapper>{children}</MusicWrapper>
      </body>
    </html>
  );
}
